### ISSUE TITLE
gcvb compute, sequential, no detach and with task report

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#11]
When debugging tests I often needs to run few of them sequentially and with a fast access to task status. Would it be possible to have a `gcvb compute` which:

* does not detach
* run sequentially
* print tests and tasks status as they are executed

Of course the `--with-jobrunner` feature should be kept to blindly run a large set of tests.

Also, even if the `job.sh` would no longer be used, it should be kept as it's a good source of information on *how my tests are run* and *how can I run a task out of gcvb*.

**Comment by jeromerobert** [comment]
As `job.sh` will be for information only, it should be split to each test folder. It's difficult to read a large `job.sh`.

**Comment by jm-cc** [comment]
16a8a688cee76fd07691e1269083f1ee486b5ed9 implements something similar to what you wanted as options for the jobrunner.

*--verbose --max-concurrent 1* will do what you want.

The large job.sh is still usefull for people that uses gcvb to launch computation on clusters (like @felsocim). AFAIK, he filters tests by number of process needed and then launch computation using *compute --header <header_for_the_computation>*

**Comment by jm-cc** [comment]
I close this since the main issue has been adressed. I will adress the job.sh issue when the multi-node launcher will be available.
