### ISSUE TITLE
Using executable placeholders from config.yaml anywhere in test definition file

### ISSUE THREAD

**Issue by felsocim** [jm-cc/gcvb#2]
In *config.yaml* it is possible to define a list of placeholders for custom programs or scripts and then use them while defining tests in a dedicated YAML file. The issue is that, the replacement works only if the placeholder is used as-is. For example, we can not use it inside of a double-quoted string.
The suggestion is to make this doable. So that, if I have the following in my *config.yaml*:
```
executables:
  parser: ../../../../../scripts/parser.sh
  rss: ../../../../../scripts/rss.py
```
I can reference either **parser** or **rss** in my test definition YAML file as follows:
```
Tasks:
  -
    launch_command: "rss {@job_creation[executable]} {@job_creation[options]} | parser"
```

**Comment by jm-cc** [comment]
Will be implemented but with a magic string like "{@from_config[executables][parser]}" instead of directly searching for the executable name in the launch_command.

**Comment by jm-cc** [comment]
Should work now. In the launch command, '{ATexecutable[<executable_name>]}' will be replaced by the executable refered by config.yaml file. If the executable does not exist, '<executable_name>' will be used instead.

AT = @ , but github interprets it as a link to a user profile.
 
see d93fc2f93b7ff413ccb4c362360d73534e2dbae5

**Comment by felsocim** [comment]
> Should work now. In the launch command, '{ATexecutable[<executable_name>]}' will be replaced by the executable refered by config.yaml file. If the executable does not exist, '<executable_name>' will be used instead.
> 
> AT = @ , but github interprets it as a link to a user profile.
> 
> see [d93fc2f](https://github.com/jm-cc/gcvb/commit/d93fc2f93b7ff413ccb4c362360d73534e2dbae5)

It does not work elsewhere but in "launch_command"?

**Comment by jm-cc** [comment]
Yes, for now it works only for the launch command.

Do you have a situation where you would like to have it expanded elsewhere ? Currently only the launch command can use the ATjob_creation and ATexecutable expansion.

**Comment by felsocim** [comment]
Ok. That's what I thought. Sorry for my late reply.

Actually, as I have defined my tests, it would be useful for me to use these tags also in `options` for example. But, I am currently adapting my definition file in such a way that I only need to use the tags within `launch_command`. It seems to be even more clear this way.
