### ISSUE TITLE
Dashboard template does not load properly

### ISSUE THREAD

**Issue by felsocim** [jm-cc/gcvb#3]
The dashboard web page uses Bootstrap. The issue is that, the link to the CSS file of Bootstrap is hard coded as a link to a file on the server which is missing. The suggestion is to either upload the missing file or use a CDN link.

**Comment by jeromerobert** [comment]
I didn't have that issue while using gcvb from it's git folder and with dependencies installed with pip. Now that I installed everything with conda and did a `pip install .` in gcvb, I get 404 on CSS files:
```
127.0.0.1 - - [13/Mar/2020 10:55:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [13/Mar/2020 10:55:44] "GET /assets/bootstrap.min.css HTTP/1.1" 404 -
127.0.0.1 - - [13/Mar/2020 10:55:44] "GET /_dash-component-suites/dash_renderer/prop-types@15.v1_2_2m1580842230.7.2.min.js HTTP/1.1" 200 -
...
127.0.0.1 - - [13/Mar/2020 10:55:47] "GET /assets/bootstrap.min.css HTTP/1.1" 404 -
127.0.0.1 - - [13/Mar/2020 10:55:47] "GET /_dash-layout HTTP/1.1" 200 -
...
127.0.0.1 - - [13/Mar/2020 10:56:12] "GET /assets/bootstrap.min.css HTTP/1.1" 404 -
...
127.0.0.1 - - [13/Mar/2020 10:56:12] "POST /_dash-update-component HTTP/1.1" 200 -
```
`assets/` files are not installed by `pip install .`

**Comment by jeromerobert** [comment]
Workaround
```
cp -a gcvb/dashboard/assets /home/robert/miniconda3/lib/python3.8/site-packages/gcvb/dashboard/

**Comment by felsocim** [comment]
Well, I am using Guix, and in this system, **gcvb** is a package installed in a global system-wide location under `/gnu/store/...` and this filesystem is read-only so I do not think that the workaround proposed by @jeromerobert can be used as is. Although, I think that I should be able to implement it to the [**gcvb** package definition](https://gitlab.inria.fr/guix-hpc/guix-hpc/-/blob/master/airbus/gcvb.scm) I will keep you posted.

**Comment by jm-cc** [comment]
So that's why I was unable to reproduce it, I always used gcvb from its git folder...  I will look into it. Plus I just realized I wasn't "watching" the gcvb repository so I missed the comment 11 days ago...
