### ISSUE TITLE
[feature] Dashboard: add links to run folder files

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#6]
I should be possible to specify file names which would be linked in the dashboard. This would be useful to add links to stdout/stderr logs or plot images.

Output files can be stored to the sqlite database using the `keep` tag. It would be nice if such file could also be linked in the dashboard.

In both case it shoul be possible to specify a content type (MIME type) to tell the web browser how to display the file. Typically:
* `Content-Type: text/html` for html file
* `Content-type: text/plain; charset=utf-8` for raw logs
* `Content-Type: image/png` for plots

IMHO the default should be `text/plain`.

**Comment by jm-cc** [comment]
Currently possible to serve files from the restult folder with the
*serve_from_result* key in the yaml which can be added in *tasks* and *validations*.

The expected value is a list of dicts with the following keys : "id, file, mimetype (optional)"

Todo : 
- documentation
- serve_from_db

**Comment by jeromerobert** [comment]
Ok `serve_from_result` works well. When `serve_from_db` will be implemented we will need a way to switch between *from DB* and *from results* mode. `gcvb dashboard --results` for example to enable *from results* mode and let the *from db* mode be the default.

**Comment by jeromerobert** [comment]
Alternatively instead of have 2 modes, we could have only one which add links to both db and results (if results is available).

**Comment by jm-cc** [comment]
Fixed in #24 (0c6dcec133b4e2fdecaa5ddf7379d1654bb3750f)
