### ISSUE TITLE
Unconsistant error report and dashboard

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#8]
To reproduce:

* Run `gcvb --filter-by-test-id mytest compute --with-jobrunner 12`
* Let mytest segfault (i.e. exit code != 0)
* Run `gcvb report` ->  `Tests completed : 1/1 Success!`
* Run `gcvb dashboard` -> No test listed

I would have expected:
* Run `gcvb report` ->  `Tests completed : 1/1 Failure!` and list of failed test
* Run `gcvb dashboard` -> mytest visible on the dashboard page (even if no results are associated). And once #6 will be implemented I will like to browse logs to understand why the test failed.

**Comment by jeromerobert** [comment]
A temporary workaround is:
* Running the jobrunner with `--verbose` and redirect output to `out.log`
* `grep 'return code' out.log |grep -v 'return code : 0'`

**Comment by jm-cc** [comment]
return codes that are different from zero are now recognized as Failure
