### ISSUE TITLE
Let jobrunner finish a test before starting a new one

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#9]
The current scheduling policy start large task first to avoid starvation at the end. It would be nice to schedule task of already started test first so we get test status as soon as possible.

As this would be less optimal than the current policy (more starvation at the end), may be this could be just an option.

**Comment by jm-cc** [comment]
Feature added in 63de43ec71c1ac6d08eab934f5fa0b6624fa749a

Just add the *--local-first* option while launching a jobrunner. It must be added for each jobrunner.
